#!/bin/bash
set -euo pipefail

# ─── Configuration ───────────────────────────────────────────────
APP_NAME="Stubble"
BUNDLE_ID="com.samattias.stubble"
VERSION="${1:-1.3.0}"                       # pass version as first arg, e.g. ./build-app.sh 1.3.0
BUILD_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="$BUILD_DIR/build"
APP_BUNDLE="$OUTPUT_DIR/$APP_NAME.app"

# Sparkle update feed — hosted on a separate public repo (source repo stays private)
SPARKLE_FEED_URL="${SPARKLE_FEED_URL:-https://github.com/samattias/stubble-releases/releases/latest/download/appcast.xml}"
# EdDSA public key — generated by Sparkle's generate_keys tool (paste yours here)
SPARKLE_ED_KEY="u/MzNL3+cpvrO3tQNKRcCbc7Fh0sOLdAOCgKupEdM/o="

# Code signing identity — Developer ID for stable TCC permissions across rebuilds
CODESIGN_IDENTITY="${CODESIGN_IDENTITY:-Developer ID Application: Sam Attias (M3QBXSJ3A2)}"
TEAM_ID="M3QBXSJ3A2"

# TelemetryDeck — app ID injected into Info.plist (not hardcoded in Swift)
TELEMETRY_DECK_APP_ID="${TELEMETRY_DECK_APP_ID:-E9AC5258-ACC0-499A-9BE7-226EC2E6E511}"

echo "🔨 Building $APP_NAME v$VERSION (both dashboard + daemon)..."
cd "$BUILD_DIR"

# Build both products in release mode
swift build -c release 2>&1

DASHBOARD_BINARY="$BUILD_DIR/.build/release/TaskMinerDashboard"

if [ ! -f "$DASHBOARD_BINARY" ]; then
    echo "❌ Dashboard build failed — binary not found"
    exit 1
fi

echo "📦 Creating $APP_NAME.app bundle..."

# Developer ID signing produces a stable identity across rebuilds,
# so TCC permissions (Screen Recording, Accessibility) persist.
rm -rf "$APP_BUNDLE"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"
mkdir -p "$APP_BUNDLE/Contents/Frameworks"

# Copy dashboard binary
cp "$DASHBOARD_BINARY" "$APP_BUNDLE/Contents/MacOS/$APP_NAME"

# Strip the linker-applied ad-hoc signature; we'll re-sign the whole
# bundle at the end with the Developer ID identity.
codesign --remove-signature "$APP_BUNDLE/Contents/MacOS/$APP_NAME" 2>/dev/null || true

# Copy app icon
ICON_SRC="$BUILD_DIR/Resources/AppIcon.icns"
if [ -f "$ICON_SRC" ]; then
    cp "$ICON_SRC" "$APP_BUNDLE/Contents/Resources/AppIcon.icns"
    echo "🎨 App icon copied"
else
    echo "⚠️  No AppIcon.icns found in Resources/ — app will use default icon"
fi

# Copy logo for setup wizard
LOGO_SRC="$BUILD_DIR/Resources/logo.png"
if [ -f "$LOGO_SRC" ]; then
    cp "$LOGO_SRC" "$APP_BUNDLE/Contents/Resources/logo.png"
fi

# ─── Bundle Sparkle.framework ────────────────────────────────────
# SPM builds Sparkle as a dynamic framework; we need to embed it in the .app
SPARKLE_FRAMEWORK=$(find "$BUILD_DIR/.build" -name "Sparkle.framework" -type d 2>/dev/null | head -1)
if [ -n "$SPARKLE_FRAMEWORK" ] && [ -d "$SPARKLE_FRAMEWORK" ]; then
    cp -R "$SPARKLE_FRAMEWORK" "$APP_BUNDLE/Contents/Frameworks/"
    echo "✨ Sparkle.framework bundled"

    # Fix rpath so the binary can find the framework at runtime
    install_name_tool -add_rpath "@executable_path/../Frameworks" "$APP_BUNDLE/Contents/MacOS/$APP_NAME" 2>/dev/null || true
else
    echo "⚠️  Sparkle.framework not found in build artifacts — auto-updates won't work"
fi

# ─── Create Info.plist ───────────────────────────────────────────
# Build Sparkle plist entries conditionally
SPARKLE_PLIST_ENTRIES="    <key>SUFeedURL</key>
    <string>$SPARKLE_FEED_URL</string>"

if [ -n "$SPARKLE_ED_KEY" ]; then
    SPARKLE_PLIST_ENTRIES="$SPARKLE_PLIST_ENTRIES
    <key>SUPublicEDKey</key>
    <string>$SPARKLE_ED_KEY</string>"
fi

cat > "$APP_BUNDLE/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleVersion</key>
    <string>$VERSION</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSSupportsAutomaticTermination</key>
    <false/>
    <key>NSAppleEventsUsageDescription</key>
    <string>Stubble needs to observe which apps you use to track your activity.</string>
    <key>NSAccessibilityUsageDescription</key>
    <string>Stubble uses Accessibility to read window titles so it can describe what you're working on.</string>
    <key>NSScreenCaptureUsageDescription</key>
    <string>Stubble captures periodic screenshots to understand what you're working on. Screenshots are stored locally and never uploaded.</string>
$SPARKLE_PLIST_ENTRIES
    <key>TelemetryDeckAppID</key>
    <string>$TELEMETRY_DECK_APP_ID</string>
</dict>
</plist>
PLIST

# Create PkgInfo
echo -n "APPL????" > "$APP_BUNDLE/Contents/PkgInfo"

# ─── Code-sign with Developer ID ──────────────────────────────────
# Sign inside-out: innermost nested binaries first, then frameworks,
# then the .app bundle. Apple discourages --deep because it signs
# nested bundles in unpredictable order and can produce invalid signatures.
# --options runtime enables the hardened runtime (required for notarization).
# --timestamp requests a secure timestamp from Apple (required for notarization).
SPARKLE_FW="$APP_BUNDLE/Contents/Frameworks/Sparkle.framework"
if [ -d "$SPARKLE_FW" ]; then
    echo "🔏 Signing Sparkle nested binaries (inside-out)..."

    # 1) XPC services (deepest nested)
    find "$SPARKLE_FW" -name "*.xpc" -type d | while read -r xpc; do
        codesign --force --sign "$CODESIGN_IDENTITY" --options runtime --timestamp "$xpc" 2>&1 || echo "   ⚠️  Failed: $xpc"
    done

    # 2) Nested apps (Updater.app)
    find "$SPARKLE_FW" -name "*.app" -type d | while read -r app; do
        codesign --force --sign "$CODESIGN_IDENTITY" --options runtime --timestamp "$app" 2>&1 || echo "   ⚠️  Failed: $app"
    done

    # 3) Standalone executables (Autoupdate)
    find "$SPARKLE_FW" -name "Autoupdate" -type f | while read -r exe; do
        codesign --force --sign "$CODESIGN_IDENTITY" --options runtime --timestamp "$exe" 2>&1 || echo "   ⚠️  Failed: $exe"
    done

    # 4) The framework itself
    codesign --force --sign "$CODESIGN_IDENTITY" --options runtime --timestamp "$SPARKLE_FW" 2>&1 || echo "   ⚠️  Sparkle framework signing failed"
fi

# 5) The main app bundle (outermost)
codesign --force --sign "$CODESIGN_IDENTITY" --options runtime --timestamp "$APP_BUNDLE" 2>&1 || echo "⚠️  App signing failed"

# Verify (strict checks match what notarization expects)
if codesign --verify --strict "$APP_BUNDLE" 2>&1; then
    echo "🔏 Signed with Developer ID + secure timestamp (✅ ready for notarization)"
else
    echo "⚠️  Signature verification failed:"
    codesign --verify --verbose "$APP_BUNDLE" 2>&1
fi

echo ""
echo "✅ Built: $APP_BUNDLE"
echo "   Version:   $VERSION"
echo "   Binary:    $(du -sh "$APP_BUNDLE/Contents/MacOS/$APP_NAME" | cut -f1)"
echo "   Total:     $(du -sh "$APP_BUNDLE" | cut -f1)"
echo ""
echo "To run:  open $APP_BUNDLE"

# ─── Create DMG (for website distribution) ─────────────────────
DMG_PATH="$OUTPUT_DIR/$APP_NAME-$VERSION.dmg"

if command -v create-dmg &>/dev/null; then
    echo ""
    echo "📀 Creating DMG..."
    # Remove existing DMG (create-dmg won't overwrite)
    rm -f "$DMG_PATH"

    # ─── Prepare staging directory ────────────────────────────────
    # We create our own Applications alias (instead of --app-drop-link)
    # so we can apply a custom orange-tinted icon to match the brand.
    DMG_STAGING=$(mktemp -d)
    cp -R "$APP_BUNDLE" "$DMG_STAGING/"

    ORANGE_ICON="$BUILD_DIR/Resources/applications-icon-orange.png"
    # Create a Finder alias to /Applications and apply orange icon
    osascript -e "tell application \"Finder\" to make new alias file at (POSIX file \"$DMG_STAGING\" as alias) to (POSIX file \"/Applications\" as alias) with properties {name:\"Applications\"}" 2>/dev/null
    if [ -f "$ORANGE_ICON" ] && [ -f "$DMG_STAGING/Applications" ]; then
        python3 -c "
from AppKit import NSWorkspace, NSImage
import os, sys
icon = NSImage.alloc().initWithContentsOfFile_(os.path.abspath('$ORANGE_ICON'))
if icon:
    result = NSWorkspace.sharedWorkspace().setIcon_forFile_options_(icon, '$DMG_STAGING/Applications', 0)
    print('🎨 Orange Applications icon applied' if result else '⚠️  Could not apply orange icon')
else:
    print('⚠️  Could not load orange icon')
" 2>/dev/null
    fi

    # ─── Build create-dmg arguments ──────────────────────────────
    DMG_ARGS=""
    if [ -f "$APP_BUNDLE/Contents/Resources/AppIcon.icns" ]; then
        DMG_ARGS="$DMG_ARGS --volicon $APP_BUNDLE/Contents/Resources/AppIcon.icns"
    fi

    BG_IMAGE="$BUILD_DIR/Resources/dmg-background.png"
    if [ -f "$BG_IMAGE" ]; then
        DMG_ARGS="$DMG_ARGS --background $BG_IMAGE"
    fi

    create-dmg \
        --volname "$APP_NAME" \
        $DMG_ARGS \
        --window-pos 200 120 \
        --window-size 600 400 \
        --icon-size 100 \
        --icon "$APP_NAME.app" 150 200 \
        --icon "Applications" 450 200 \
        --no-internet-enable \
        "$DMG_PATH" \
        "$DMG_STAGING" \
        2>&1 || true  # create-dmg exits 2 when it can't sign the DMG (expected with ad-hoc)

    rm -rf "$DMG_STAGING"

    if [ -f "$DMG_PATH" ]; then
        echo "✅ DMG: $DMG_PATH ($(du -sh "$DMG_PATH" | cut -f1))"
    else
        echo "⚠️  DMG creation failed — install create-dmg: brew install create-dmg"
    fi
else
    echo ""
    echo "💡 To create a DMG for website distribution: brew install create-dmg"
fi

echo ""
echo "── To publish a release ────────────────────────────────────"
echo "   bash scripts/publish-update.sh"
echo ""
