#!/bin/bash
set -euo pipefail

# ─── Load local config (gitignored) ──────────────────────────────
# Create scripts/.local-config with your Developer ID, e.g.:
#   export CODESIGN_IDENTITY="Developer ID Application: Your Name (TEAMID)"
#   export TEAM_ID="TEAMID"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/.local-config" ]; then
    source "$SCRIPT_DIR/.local-config"
fi

# ─── Configuration ───────────────────────────────────────────────
# These can be overridden via environment variables for self-hosted builds.
APP_NAME="${APP_NAME:-Stubble}"
BUNDLE_ID="${BUNDLE_ID:-com.stubbleapp.desktop}"
GITHUB_REPO="${GITHUB_REPO:-stubbleapp/stubble-releases}"

# ─── Version: explicit arg, or auto-increment from latest release ─
if [ -n "${1:-}" ]; then
    VERSION="$1"
else
    # Query latest release tag from GitHub (e.g. "v1.7.0" → "1.7.0")
    LATEST_TAG=$(gh release view --repo "$GITHUB_REPO" --json tagName -q '.tagName' 2>/dev/null || echo "")
    if [ -n "$LATEST_TAG" ]; then
        LATEST_VERSION="${LATEST_TAG#v}"  # strip leading 'v'
        # Split into major.minor.patch and bump minor
        IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_VERSION"
        MINOR=$((MINOR + 1))
        VERSION="$MAJOR.$MINOR.0"
        echo "📌 Latest release: $LATEST_TAG → auto-incrementing to v$VERSION"
    else
        VERSION="1.0.0"
        echo "📌 No existing releases found — starting at v$VERSION"
    fi
fi
BUILD_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="$BUILD_DIR/build"
APP_BUNDLE="$OUTPUT_DIR/$APP_NAME.app"

# Sparkle update feed — hosted on a separate public repo (source repo stays private)
# Set to empty string to disable auto-updates for self-hosted builds.
SPARKLE_FEED_URL="${SPARKLE_FEED_URL:-https://github.com/stubbleapp/stubble-releases/releases/latest/download/appcast.xml}"

# EdDSA public key — generated by Sparkle's generate_keys tool.
# Set to empty string to disable Sparkle signature verification (for self-hosted builds).
SPARKLE_ED_KEY="${SPARKLE_ED_KEY:-u/MzNL3+cpvrO3tQNKRcCbc7Fh0sOLdAOCgKupEdM/o=}"

# Code signing identity — Developer ID for stable TCC permissions across rebuilds.
# Set to "-" for ad-hoc signing (self-hosted builds).
# Configure in scripts/.local-config (gitignored) for local development.
CODESIGN_IDENTITY="${CODESIGN_IDENTITY:-}"

# Team ID for code signing. Set to empty string for self-hosted builds.
TEAM_ID="${TEAM_ID:-}"

# TelemetryDeck — app ID injected into Info.plist (not hardcoded in Swift).
# Set to empty string to disable analytics for self-hosted builds.
TELEMETRY_DECK_APP_ID="${TELEMETRY_DECK_APP_ID:-E9AC5258-ACC0-499A-9BE7-226EC2E6E511}"

# ─── Certificate Expiry Check ─────────────────────────────────────
# Developer ID certificates expire after 5 years — warn if expiring soon
CERT_INFO=$(security find-certificate -c "Developer ID Application" -p 2>/dev/null | openssl x509 -noout -enddate -subject 2>/dev/null || true)
if [ -n "$CERT_INFO" ]; then
    CERT_EXPIRY=$(echo "$CERT_INFO" | grep notAfter | cut -d= -f2)
    if [ -n "$CERT_EXPIRY" ]; then
        EXPIRY_EPOCH=$(date -j -f "%b %d %T %Y %Z" "$CERT_EXPIRY" "+%s" 2>/dev/null || true)
        NOW_EPOCH=$(date "+%s")
        if [ -n "$EXPIRY_EPOCH" ]; then
            DAYS_LEFT=$(( (EXPIRY_EPOCH - NOW_EPOCH) / 86400 ))
            if [ "$DAYS_LEFT" -lt 30 ]; then
                echo "⚠️  WARNING: Developer ID certificate expires in $DAYS_LEFT days ($CERT_EXPIRY)"
            elif [ "$DAYS_LEFT" -lt 90 ]; then
                echo "📜 Certificate expires in $DAYS_LEFT days ($CERT_EXPIRY)"
            fi
        fi
    fi
fi

echo "🔨 Building $APP_NAME v$VERSION (both dashboard + daemon)..."
cd "$BUILD_DIR"

# Build both products in release mode with size optimization
# -Osize produces 5-30% smaller binaries while maintaining good performance
swift build -c release -Xswiftc -Osize 2>&1

DASHBOARD_BINARY="$BUILD_DIR/.build/release/TaskMinerDashboard"

if [ ! -f "$DASHBOARD_BINARY" ]; then
    echo "❌ Dashboard build failed — binary not found"
    exit 1
fi

# ─── Generate dSYM for crash symbolication ────────────────────────
# dSYMs are required to make sense of crash reports from users
DSYM_DIR="$OUTPUT_DIR/dSYMs"
mkdir -p "$DSYM_DIR"
DSYM_PATH="$DSYM_DIR/$APP_NAME-$VERSION.dSYM"
if dsymutil "$DASHBOARD_BINARY" -o "$DSYM_PATH" 2>/dev/null; then
    echo "🔍 dSYM generated: $DSYM_PATH"
else
    echo "⚠️  dSYM generation failed (crash symbolication won't work)"
fi

echo "📦 Creating $APP_NAME.app bundle..."

# Developer ID signing produces a stable identity across rebuilds,
# so TCC permissions (Screen Recording, Accessibility) persist.
rm -rf "$APP_BUNDLE"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"
mkdir -p "$APP_BUNDLE/Contents/Frameworks"

# Copy dashboard binary
cp "$DASHBOARD_BINARY" "$APP_BUNDLE/Contents/MacOS/$APP_NAME"

# Strip debug symbols for smaller binary (dSYM already generated above)
strip -x "$APP_BUNDLE/Contents/MacOS/$APP_NAME" 2>/dev/null || true

# Strip the linker-applied ad-hoc signature; we'll re-sign the whole
# bundle at the end with the Developer ID identity.
codesign --remove-signature "$APP_BUNDLE/Contents/MacOS/$APP_NAME" 2>/dev/null || true

# Copy stubble-mcp binary (MCP server for AI agent access)
MCP_BINARY="$BUILD_DIR/.build/release/stubble-mcp"
if [ -f "$MCP_BINARY" ]; then
    cp "$MCP_BINARY" "$APP_BUNDLE/Contents/MacOS/stubble-mcp"
    strip -x "$APP_BUNDLE/Contents/MacOS/stubble-mcp" 2>/dev/null || true
    codesign --remove-signature "$APP_BUNDLE/Contents/MacOS/stubble-mcp" 2>/dev/null || true
    echo "🔌 MCP server bundled (stubble-mcp)"
fi

# Copy app icon
ICON_SRC="$BUILD_DIR/Resources/AppIcon.icns"
if [ -f "$ICON_SRC" ]; then
    cp "$ICON_SRC" "$APP_BUNDLE/Contents/Resources/AppIcon.icns"
    echo "🎨 App icon copied"
else
    echo "⚠️  No AppIcon.icns found in Resources/ — app will use default icon"
fi

# Copy logo for setup wizard
LOGO_SRC="$BUILD_DIR/Resources/logo.png"
if [ -f "$LOGO_SRC" ]; then
    cp "$LOGO_SRC" "$APP_BUNDLE/Contents/Resources/logo.png"
fi

# Copy custom fonts
FONTS_DIR="$BUILD_DIR/Resources/Fonts"
if [ -d "$FONTS_DIR" ]; then
    mkdir -p "$APP_BUNDLE/Contents/Resources/Fonts"
    cp "$FONTS_DIR"/*.ttf "$APP_BUNDLE/Contents/Resources/Fonts/" 2>/dev/null
    echo "🔤 Custom fonts copied"
fi

# Copy Connect tab icons
CONNECT_ICONS_DIR="$BUILD_DIR/Resources/ConnectIcons"
if [ -d "$CONNECT_ICONS_DIR" ]; then
    mkdir -p "$APP_BUNDLE/Contents/Resources/ConnectIcons"
    cp "$CONNECT_ICONS_DIR"/*.png "$APP_BUNDLE/Contents/Resources/ConnectIcons/" 2>/dev/null
    echo "🔗 Connect icons copied"
fi

# Copy Claude Desktop skills
SKILLS_DIR="$BUILD_DIR/Resources/Skills"
if [ -d "$SKILLS_DIR" ]; then
    mkdir -p "$APP_BUNDLE/Contents/Resources/Skills"
    cp "$SKILLS_DIR"/*.skill "$APP_BUNDLE/Contents/Resources/Skills/" 2>/dev/null
    echo "🎯 Claude Desktop skills copied"
fi

# Build MCPB extension for Claude Desktop (not bundled, published separately)
if [ -f "$BUILD_DIR/scripts/build-mcpb.sh" ]; then
    bash "$BUILD_DIR/scripts/build-mcpb.sh" >/dev/null 2>&1 || true
    if [ -f "$OUTPUT_DIR/Stubble.mcpb" ]; then
        echo "📦 MCPB extension built (publish separately to stubbleapp/stubble-mcpb)"
    fi
fi

# ─── Bundle Sparkle.framework ────────────────────────────────────
# SPM builds Sparkle as a dynamic framework; we need to embed it in the .app
SPARKLE_FRAMEWORK=$(find "$BUILD_DIR/.build" -name "Sparkle.framework" -type d 2>/dev/null | head -1)
if [ -n "$SPARKLE_FRAMEWORK" ] && [ -d "$SPARKLE_FRAMEWORK" ]; then
    cp -R "$SPARKLE_FRAMEWORK" "$APP_BUNDLE/Contents/Frameworks/"
    echo "✨ Sparkle.framework bundled"

    # Fix rpath so the binary can find the framework at runtime
    install_name_tool -add_rpath "@executable_path/../Frameworks" "$APP_BUNDLE/Contents/MacOS/$APP_NAME" 2>/dev/null || true
else
    echo "⚠️  Sparkle.framework not found in build artifacts — auto-updates won't work"
fi

# ─── Create Info.plist ───────────────────────────────────────────
# Build Sparkle plist entries conditionally (only if feed URL is set)
SPARKLE_PLIST_ENTRIES=""
if [ -n "$SPARKLE_FEED_URL" ]; then
    SPARKLE_PLIST_ENTRIES="    <key>SUFeedURL</key>
    <string>$SPARKLE_FEED_URL</string>"

    if [ -n "$SPARKLE_ED_KEY" ]; then
        SPARKLE_PLIST_ENTRIES="$SPARKLE_PLIST_ENTRIES
    <key>SUPublicEDKey</key>
    <string>$SPARKLE_ED_KEY</string>
    <key>SUEnableAutomaticChecks</key>
    <true/>
    <key>SUAllowsAutomaticUpdates</key>
    <true/>"
    fi
fi

# Build TelemetryDeck plist entry conditionally
TELEMETRY_PLIST_ENTRY=""
if [ -n "$TELEMETRY_DECK_APP_ID" ]; then
    TELEMETRY_PLIST_ENTRY="    <key>TelemetryDeckAppID</key>
    <string>$TELEMETRY_DECK_APP_ID</string>"
fi

# Build Supabase/API credentials plist entries (from .local-config)
API_PLIST_ENTRIES=""
if [ -n "$STUBBLE_SUPABASE_URL" ]; then
    API_PLIST_ENTRIES="    <key>STUBBLE_SUPABASE_URL</key>
    <string>$STUBBLE_SUPABASE_URL</string>"
fi
if [ -n "$STUBBLE_SUPABASE_ANON_KEY" ]; then
    API_PLIST_ENTRIES="$API_PLIST_ENTRIES
    <key>STUBBLE_SUPABASE_ANON_KEY</key>
    <string>$STUBBLE_SUPABASE_ANON_KEY</string>"
fi
if [ -n "$STUBBLE_PROXY_URL" ]; then
    API_PLIST_ENTRIES="$API_PLIST_ENTRIES
    <key>STUBBLE_PROXY_URL</key>
    <string>$STUBBLE_PROXY_URL</string>"
fi

cat > "$APP_BUNDLE/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleVersion</key>
    <string>$VERSION</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSSupportsAutomaticTermination</key>
    <false/>
    <key>NSAppleEventsUsageDescription</key>
    <string>Stubble needs to observe which apps you use to track your activity.</string>
    <key>NSAccessibilityUsageDescription</key>
    <string>Stubble uses Accessibility to read window titles so it can describe what you're working on.</string>
    <key>NSScreenCaptureUsageDescription</key>
    <string>Stubble captures periodic screenshots to understand what you're working on. Screenshots are stored locally and never uploaded.</string>
    <key>NSCalendarsUsageDescription</key>
    <string>Stubble reads your calendar to provide meeting context in your daily activity summary. Event data stays on your device.</string>
    <key>NSCalendarsFullAccessUsageDescription</key>
    <string>Stubble reads your calendar to provide meeting context in your daily activity summary. Event data stays on your device.</string>
    <key>ATSApplicationFontsPath</key>
    <string>Fonts</string>
$SPARKLE_PLIST_ENTRIES
$TELEMETRY_PLIST_ENTRY
$API_PLIST_ENTRIES
    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>com.stubble</string>
            </array>
            <key>CFBundleURLName</key>
            <string>com.stubble.auth</string>
        </dict>
    </array>
</dict>
</plist>
PLIST

# Create PkgInfo
echo -n "APPL????" > "$APP_BUNDLE/Contents/PkgInfo"

# ─── Code-sign with Developer ID or ad-hoc ──────────────────────────────────
# Sign inside-out: innermost nested binaries first, then frameworks,
# then the .app bundle. Apple discourages --deep because it signs
# nested bundles in unpredictable order and can produce invalid signatures.
# --options runtime enables the hardened runtime (required for notarization).
# --timestamp requests a secure timestamp from Apple (required for notarization).

# Determine signing mode: Developer ID, ad-hoc, or none
USE_ADHOC=0
if [ -z "$CODESIGN_IDENTITY" ] || [ "$CODESIGN_IDENTITY" = "-" ]; then
    USE_ADHOC=1
    CODESIGN_IDENTITY="-"
    echo "🔏 Using ad-hoc signing (self-hosted build)"
fi

SPARKLE_FW="$APP_BUNDLE/Contents/Frameworks/Sparkle.framework"
SIGN_FAILED=0

# Build codesign options based on signing mode
if [ "$USE_ADHOC" -eq 1 ]; then
    # Ad-hoc: no timestamp, no hardened runtime (notarization not possible)
    SIGN_OPTS="--force --sign -"
else
    # Developer ID: hardened runtime + timestamp for notarization
    SIGN_OPTS="--force --sign \"$CODESIGN_IDENTITY\" --options runtime --timestamp"
fi

if [ -d "$SPARKLE_FW" ]; then
    echo "🔏 Signing Sparkle nested binaries (inside-out)..."

    # 1) XPC services (deepest nested)
    while IFS= read -r -d '' xpc; do
        eval codesign $SIGN_OPTS "$xpc" 2>&1 || SIGN_FAILED=1
    done < <(find "$SPARKLE_FW" -name "*.xpc" -type d -print0)

    # 2) Nested apps (Updater.app)
    while IFS= read -r -d '' app; do
        eval codesign $SIGN_OPTS "$app" 2>&1 || SIGN_FAILED=1
    done < <(find "$SPARKLE_FW" -name "*.app" -type d -print0)

    # 3) Standalone executables (Autoupdate)
    while IFS= read -r -d '' exe; do
        eval codesign $SIGN_OPTS "$exe" 2>&1 || SIGN_FAILED=1
    done < <(find "$SPARKLE_FW" -name "Autoupdate" -type f -print0)

    # 4) The framework itself
    eval codesign $SIGN_OPTS "$SPARKLE_FW" 2>&1 || SIGN_FAILED=1
fi

# 5) Sign stubble-mcp binary (if present)
if [ -f "$APP_BUNDLE/Contents/MacOS/stubble-mcp" ]; then
    eval codesign $SIGN_OPTS "$APP_BUNDLE/Contents/MacOS/stubble-mcp" 2>&1 || SIGN_FAILED=1
fi

# 6) The main app bundle (outermost) — with entitlements
ENTITLEMENTS="$BUILD_DIR/Resources/Stubble.entitlements"
if [ -f "$ENTITLEMENTS" ] && [ "$USE_ADHOC" -eq 0 ]; then
    eval codesign $SIGN_OPTS --entitlements "$ENTITLEMENTS" "$APP_BUNDLE" 2>&1 || SIGN_FAILED=1
else
    eval codesign $SIGN_OPTS "$APP_BUNDLE" 2>&1 || SIGN_FAILED=1
fi

if [ "$SIGN_FAILED" -ne 0 ]; then
    echo "❌ One or more code signing steps failed"
    exit 1
fi

# Verify signature
if codesign --verify --strict "$APP_BUNDLE" 2>&1; then
    if [ "$USE_ADHOC" -eq 1 ]; then
        echo "🔏 Signed with ad-hoc identity (⚠️ not suitable for distribution)"
    else
        echo "🔏 Signed with Developer ID + secure timestamp (✅ ready for notarization)"
    fi
else
    echo "❌ Signature verification failed:"
    codesign --verify --verbose "$APP_BUNDLE" 2>&1
    exit 1
fi

echo ""
echo "✅ Built: $APP_BUNDLE"
echo "   Version:   $VERSION"
echo "   Binary:    $(du -sh "$APP_BUNDLE/Contents/MacOS/$APP_NAME" | cut -f1)"
echo "   Total:     $(du -sh "$APP_BUNDLE" | cut -f1)"
echo ""
echo "To run:  open $APP_BUNDLE"

# ─── Create DMG (for website distribution) ─────────────────────
DMG_PATH="$OUTPUT_DIR/$APP_NAME-$VERSION.dmg"

if command -v create-dmg &>/dev/null; then
    echo ""
    echo "📀 Creating DMG..."
    # Remove existing DMG (create-dmg won't overwrite)
    rm -f "$DMG_PATH"

    # ─── Prepare staging directory ────────────────────────────────
    # We create our own Applications alias (instead of --app-drop-link)
    # so we can apply a custom orange-tinted icon to match the brand.
    DMG_STAGING=$(mktemp -d)
    cp -R "$APP_BUNDLE" "$DMG_STAGING/"

    ORANGE_ICON="$BUILD_DIR/Resources/applications-icon-orange.png"
    # Create a Finder alias to /Applications and apply orange icon
    osascript -e "tell application \"Finder\" to make new alias file at (POSIX file \"$DMG_STAGING\" as alias) to (POSIX file \"/Applications\" as alias) with properties {name:\"Applications\"}" 2>/dev/null
    if [ -f "$ORANGE_ICON" ] && [ -f "$DMG_STAGING/Applications" ]; then
        python3 -c "
from AppKit import NSWorkspace, NSImage
import os, sys
icon = NSImage.alloc().initWithContentsOfFile_(os.path.abspath('$ORANGE_ICON'))
if icon:
    result = NSWorkspace.sharedWorkspace().setIcon_forFile_options_(icon, '$DMG_STAGING/Applications', 0)
    print('🎨 Orange Applications icon applied' if result else '⚠️  Could not apply orange icon')
else:
    print('⚠️  Could not load orange icon')
" 2>/dev/null
    fi

    # ─── Build create-dmg arguments ──────────────────────────────
    DMG_ARGS=""
    if [ -f "$APP_BUNDLE/Contents/Resources/AppIcon.icns" ]; then
        DMG_ARGS="$DMG_ARGS --volicon $APP_BUNDLE/Contents/Resources/AppIcon.icns"
    fi

    BG_IMAGE="$BUILD_DIR/Resources/dmg-background.png"
    if [ -f "$BG_IMAGE" ]; then
        DMG_ARGS="$DMG_ARGS --background $BG_IMAGE"
    fi

    create-dmg \
        --volname "$APP_NAME" \
        $DMG_ARGS \
        --window-pos 200 120 \
        --window-size 600 400 \
        --icon-size 100 \
        --icon "$APP_NAME.app" 150 200 \
        --icon "Applications" 450 200 \
        --no-internet-enable \
        "$DMG_PATH" \
        "$DMG_STAGING" \
        2>&1 || true  # create-dmg exits 2 when it can't sign the DMG (expected with ad-hoc)

    rm -rf "$DMG_STAGING"

    # Handle create-dmg temp file naming (rw.XXXXX.Stubble-VERSION.dmg)
    if [ ! -f "$DMG_PATH" ]; then
        TEMP_DMG=$(ls "$OUTPUT_DIR"/rw.*.$APP_NAME-$VERSION.dmg 2>/dev/null | head -1)
        if [ -n "$TEMP_DMG" ] && [ -f "$TEMP_DMG" ]; then
            mv "$TEMP_DMG" "$DMG_PATH"
            echo "🎨 DMG renamed from temp file"
        fi
    fi

    if [ -f "$DMG_PATH" ]; then
        echo "✅ DMG: $DMG_PATH ($(du -sh "$DMG_PATH" | cut -f1))"
    else
        echo "⚠️  DMG creation failed — install create-dmg: brew install create-dmg"
    fi
else
    echo ""
    echo "💡 To create a DMG for website distribution: brew install create-dmg"
fi

echo ""
echo "── To publish a release ────────────────────────────────────"
echo "   bash scripts/publish-update.sh"
echo ""
echo "── To profile launch time ──────────────────────────────────"
echo "   xcrun xctrace record --template 'App Launch' --launch '$APP_BUNDLE' --output launch.trace"
echo "   open launch.trace"
echo ""
