#!/bin/bash
set -euo pipefail

# ─── Configuration ───────────────────────────────────────────────
APP_NAME="Stubble"
BUNDLE_ID="com.samattias.stubble"
VERSION="${1:-1.0.0}"                       # pass version as first arg, e.g. ./build-app.sh 1.2.0
BUILD_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="$BUILD_DIR/build"
APP_BUNDLE="$OUTPUT_DIR/$APP_NAME.app"

# Sparkle update feed — hosted on a separate public repo (source repo stays private)
SPARKLE_FEED_URL="${SPARKLE_FEED_URL:-https://github.com/samattias/stubble-releases/releases/latest/download/appcast.xml}"
# EdDSA public key — generated by Sparkle's generate_keys tool (paste yours here)
SPARKLE_ED_KEY="u/MzNL3+cpvrO3tQNKRcCbc7Fh0sOLdAOCgKupEdM/o="

echo "🔨 Building $APP_NAME v$VERSION (both dashboard + daemon)..."
cd "$BUILD_DIR"

# Build both products in release mode
swift build -c release 2>&1

DASHBOARD_BINARY="$BUILD_DIR/.build/release/TaskMinerDashboard"

if [ ! -f "$DASHBOARD_BINARY" ]; then
    echo "❌ Dashboard build failed — binary not found"
    exit 1
fi

echo "📦 Creating $APP_NAME.app bundle..."

# Clean previous build
rm -rf "$APP_BUNDLE"

# Create .app directory structure
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"
mkdir -p "$APP_BUNDLE/Contents/Frameworks"

# Copy dashboard binary (it also contains the daemon code — single binary for permissions)
cp "$DASHBOARD_BINARY" "$APP_BUNDLE/Contents/MacOS/$APP_NAME"

# Strip the linker-applied ad-hoc signature; we'll re-sign the whole
# bundle at the end so every build has the same identity ("-").
codesign --remove-signature "$APP_BUNDLE/Contents/MacOS/$APP_NAME" 2>/dev/null || true

# Copy app icon
ICON_SRC="$BUILD_DIR/Resources/AppIcon.icns"
if [ -f "$ICON_SRC" ]; then
    cp "$ICON_SRC" "$APP_BUNDLE/Contents/Resources/AppIcon.icns"
    echo "🎨 App icon copied"
else
    echo "⚠️  No AppIcon.icns found in Resources/ — app will use default icon"
fi

# ─── Bundle Sparkle.framework ────────────────────────────────────
# SPM builds Sparkle as a dynamic framework; we need to embed it in the .app
SPARKLE_FRAMEWORK=$(find "$BUILD_DIR/.build" -name "Sparkle.framework" -type d 2>/dev/null | head -1)
if [ -n "$SPARKLE_FRAMEWORK" ] && [ -d "$SPARKLE_FRAMEWORK" ]; then
    cp -R "$SPARKLE_FRAMEWORK" "$APP_BUNDLE/Contents/Frameworks/"
    echo "✨ Sparkle.framework bundled"

    # Fix rpath so the binary can find the framework at runtime
    install_name_tool -add_rpath "@executable_path/../Frameworks" "$APP_BUNDLE/Contents/MacOS/$APP_NAME" 2>/dev/null || true
else
    echo "⚠️  Sparkle.framework not found in build artifacts — auto-updates won't work"
fi

# ─── Create Info.plist ───────────────────────────────────────────
# Build Sparkle plist entries conditionally
SPARKLE_PLIST_ENTRIES="    <key>SUFeedURL</key>
    <string>$SPARKLE_FEED_URL</string>"

if [ -n "$SPARKLE_ED_KEY" ]; then
    SPARKLE_PLIST_ENTRIES="$SPARKLE_PLIST_ENTRIES
    <key>SUPublicEDKey</key>
    <string>$SPARKLE_ED_KEY</string>"
fi

cat > "$APP_BUNDLE/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleVersion</key>
    <string>$VERSION</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSSupportsAutomaticTermination</key>
    <false/>
    <key>NSAppleEventsUsageDescription</key>
    <string>Stubble needs to observe which apps you use to track your activity.</string>
    <key>NSAccessibilityUsageDescription</key>
    <string>Stubble uses Accessibility to read window titles so it can describe what you're working on.</string>
    <key>NSScreenCaptureUsageDescription</key>
    <string>Stubble captures periodic screenshots to understand what you're working on. Screenshots are stored locally and never uploaded.</string>
$SPARKLE_PLIST_ENTRIES
</dict>
</plist>
PLIST

# Create PkgInfo
echo -n "APPL????" > "$APP_BUNDLE/Contents/PkgInfo"

# ─── Ad-hoc code-sign the whole bundle ────────────────────────────
# We stripped the per-binary linker signatures above. Now re-sign the
# entire .app with an explicit ad-hoc identity so that:
#   1) macOS will actually launch the app (unsigned binaries are blocked)
#   2) Every build uses the same signing identity ("-"), so Sparkle
#      won't reject updates due to identity mismatches.
codesign --force --deep --sign - "$APP_BUNDLE" 2>/dev/null || true

# Create StubbleDaemon as a hard-link to the signed Stubble binary.
# This MUST be after codesign because signing replaces the file and breaks links.
# Same inode = same binary = same macOS permission grant for both processes.
ln -f "$APP_BUNDLE/Contents/MacOS/$APP_NAME" "$APP_BUNDLE/Contents/MacOS/StubbleDaemon"
echo "🔏 Ad-hoc signed"

echo ""
echo "✅ Built: $APP_BUNDLE"
echo "   Version:   $VERSION"
echo "   Binary:    $(du -sh "$APP_BUNDLE/Contents/MacOS/$APP_NAME" | cut -f1)"
echo "   Total:     $(du -sh "$APP_BUNDLE" | cut -f1)"
echo ""
echo "To run:  open $APP_BUNDLE"
echo ""
echo "── Publishing an update ──────────────────────────────────────"
echo "   cd $OUTPUT_DIR && zip -r $APP_NAME-$VERSION.zip $APP_NAME.app"
echo "   # Sign the zip with Sparkle's sign_update tool:"
echo "   #   .build/artifacts/sparkle/Sparkle/bin/sign_update $APP_NAME-$VERSION.zip"
echo "   # Then run generate_appcast on your updates folder."
echo ""
