import Foundation
import CryptoKit
import TaskMinerShared

/// A higher-level grouping of related tasks into a project or activity stream.
/// Generated by clustering TaskRecords via AI and persisted to the database.
struct ProjectActivity: Identifiable {
    let id: UUID
    let name: String                    // e.g., "TaskMiner Dashboard Development"
    let summary: String                 // 1-2 sentence description of work done
    let totalDuration: TimeInterval     // Sum of constituent task durations
    let appNames: [String]              // Union of apps across all tasks
    let taskTitles: [String]            // Titles of constituent tasks (for expand)
    let startTime: Date                 // Earliest task start
    let endTime: Date                   // Latest task end
    let colorIndex: Int                 // Stable index into Theme.barPalette

    /// Create a stable color index from the project name so the same project
    /// always gets the same color even after re-generation.
    static func stableColorIndex(for name: String, paletteSize: Int) -> Int {
        var hash: UInt64 = 5381
        for byte in name.lowercased().utf8 {
            hash = ((hash &<< 5) &+ hash) &+ UInt64(byte) // djb2
        }
        return Int(hash % UInt64(paletteSize))
    }
}

extension ProjectActivity: Hashable {
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
    static func == (lhs: ProjectActivity, rhs: ProjectActivity) -> Bool {
        lhs.id == rhs.id
    }
}

extension ProjectActivity {
    /// Derive a stable UUID from date + name so the same project keeps its
    /// identity across data reloads (preserving UI expansion state, etc.).
    private static func stableID(date: String, name: String) -> UUID {
        let data = Data((date + "|" + name).utf8)
        let hash = SHA256.hash(data: data)
        let bytes = Array(hash)
        // Use first 16 bytes of SHA-256 as a UUID
        return UUID(uuid: (
            bytes[0], bytes[1], bytes[2], bytes[3],
            bytes[4], bytes[5], bytes[6], bytes[7],
            bytes[8], bytes[9], bytes[10], bytes[11],
            bytes[12], bytes[13], bytes[14], bytes[15]
        ))
    }

    /// Create from a database record.
    init(from record: ProjectActivityRecord) {
        self.init(
            id: Self.stableID(date: record.date, name: record.name),
            name: record.name,
            summary: record.summary,
            totalDuration: record.totalDuration,
            appNames: record.appNamesList,
            taskTitles: record.taskTitlesList,
            startTime: record.startTime,
            endTime: record.endTime,
            colorIndex: record.colorIndex
        )
    }

    /// Convert to a database record for persistence.
    func toRecord(date: String) -> ProjectActivityRecord {
        let appNamesJSON: String
        if let data = try? JSONSerialization.data(withJSONObject: appNames),
           let str = String(data: data, encoding: .utf8) {
            appNamesJSON = str
        } else {
            appNamesJSON = "[]"
        }

        let taskTitlesJSON: String
        if let data = try? JSONSerialization.data(withJSONObject: taskTitles),
           let str = String(data: data, encoding: .utf8) {
            taskTitlesJSON = str
        } else {
            taskTitlesJSON = "[]"
        }

        return ProjectActivityRecord(
            date: date,
            name: name,
            summary: summary,
            totalDuration: totalDuration,
            appNames: appNamesJSON,
            taskTitles: taskTitlesJSON,
            startTime: startTime,
            endTime: endTime,
            colorIndex: colorIndex
        )
    }

    /// Convert to an AggregatedProject for use with ProjectDetailSheet.
    /// Creates a single-day aggregation with minimal work pattern data.
    func toAggregatedProject() -> AggregatedProject {
        let weekday = Calendar.current.component(.weekday, from: startTime)
        let startHour = Calendar.current.component(.hour, from: startTime)
        let endHour = Calendar.current.component(.hour, from: endTime)

        // Distribute duration across hours worked
        var hourlyDistribution: [Int: TimeInterval] = [:]
        let hoursWorked = max(1, endHour - startHour + 1)
        let durationPerHour = totalDuration / Double(hoursWorked)
        for hour in startHour...endHour {
            hourlyDistribution[hour] = durationPerHour
        }

        // Single day's data
        let dayStart = Calendar.current.startOfDay(for: startTime)

        return AggregatedProject(
            id: AggregatedProject.stableID(for: name),
            name: name,
            summary: summary,
            totalDuration: totalDuration,
            daysActive: 1,
            appNames: Set(appNames),
            taskTitles: taskTitles,
            colorIndex: colorIndex,
            weekdayDistribution: [weekday: totalDuration],
            hourlyDistribution: hourlyDistribution,
            dailyDurations: [dayStart: totalDuration],
            firstActiveDate: startTime,
            lastActiveDate: endTime
        )
    }
}
