import Foundation
import TaskMinerShared

/// A higher-level grouping of related tasks into a project or activity stream.
/// Generated by clustering TaskRecords via AI and persisted to the database.
struct ProjectActivity: Identifiable {
    let id: UUID
    let name: String                    // e.g., "TaskMiner Dashboard Development"
    let summary: String                 // 1-2 sentence description of work done
    let totalDuration: TimeInterval     // Sum of constituent task durations
    let appNames: [String]              // Union of apps across all tasks
    let taskTitles: [String]            // Titles of constituent tasks (for expand)
    let startTime: Date                 // Earliest task start
    let endTime: Date                   // Latest task end
    let colorIndex: Int                 // Stable index into Theme.barPalette

    /// Create a stable color index from the project name so the same project
    /// always gets the same color even after re-generation.
    static func stableColorIndex(for name: String, paletteSize: Int) -> Int {
        var hash: UInt64 = 5381
        for byte in name.lowercased().utf8 {
            hash = ((hash &<< 5) &+ hash) &+ UInt64(byte) // djb2
        }
        return Int(hash % UInt64(paletteSize))
    }
}

extension ProjectActivity: Hashable {
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
    static func == (lhs: ProjectActivity, rhs: ProjectActivity) -> Bool {
        lhs.id == rhs.id
    }
}

extension ProjectActivity {
    /// Create from a database record.
    init(from record: ProjectActivityRecord) {
        self.init(
            id: UUID(),
            name: record.name,
            summary: record.summary,
            totalDuration: record.totalDuration,
            appNames: record.appNamesList,
            taskTitles: record.taskTitlesList,
            startTime: record.startTime,
            endTime: record.endTime,
            colorIndex: record.colorIndex
        )
    }

    /// Convert to a database record for persistence.
    func toRecord(date: String) -> ProjectActivityRecord {
        let appNamesJSON: String
        if let data = try? JSONSerialization.data(withJSONObject: appNames),
           let str = String(data: data, encoding: .utf8) {
            appNamesJSON = str
        } else {
            appNamesJSON = "[]"
        }

        let taskTitlesJSON: String
        if let data = try? JSONSerialization.data(withJSONObject: taskTitles),
           let str = String(data: data, encoding: .utf8) {
            taskTitlesJSON = str
        } else {
            taskTitlesJSON = "[]"
        }

        return ProjectActivityRecord(
            date: date,
            name: name,
            summary: summary,
            totalDuration: totalDuration,
            appNames: appNamesJSON,
            taskTitles: taskTitlesJSON,
            startTime: startTime,
            endTime: endTime,
            colorIndex: colorIndex
        )
    }
}
